name: yolo-toy
channels:
  - pytorch
  - nvidia        # Required for CUDA dependencies
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchmetrics
  - pytorch-cuda  # Forces PyTorch to install with CUDA support
  - numpy
  - opencv        # Installs cv2
  - pycocotools